name = "FPV AI Drones";
picture = "logo.paa";  // Optional
actionName = "GitHub";
action = "https://github.com/yourusername/fpv_ai_drones";  // Optional
description = "AI-controlled FPV kamikaze drones that target vehicles";
logo = "logo.paa";  // Optional
logoOver = "logo.paa";  // Optional
tooltip = "FPV AI Drones";
tooltipOwned = "FPV AI Drones Owned";
overview = "This mod adds AI-controlled FPV kamikaze drones that automatically target and attack enemy vehicles.";
author = "Your Name";
version = "1.0.0"; 